# Generated by Django 2.2.3 on 2019-07-21 15:48

import apps.house_rent.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        ('proprietary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('bedroom_number', models.SmallIntegerField(blank=True, null=True)),
                ('bathroom_number', models.SmallIntegerField(blank=True, null=True)),
                ('construcction_size', models.IntegerField(blank=True, null=True)),
                ('solar_size', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('city', models.CharField(choices=[('SD', 'Santo Domingo'), ('SC', 'San Cristobal'), ('SA', 'Santiago')], default='SD', max_length=4)),
                ('deleted', models.BooleanField(default=False)),
                ('proprietary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietary.Proprietary')),
            ],
        ),
        migrations.CreateModel(
            name='HouseRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtention_date', models.DateField()),
                ('begin_living_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_rent.House')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.house_rent.helpers.user_house_directory_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='house_rent.House')),
            ],
        ),
    ]
