# Generated by Django 2.2.3 on 2019-07-17 17:22

import apps.place_rent.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propietary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('bedroom_number', models.SmallIntegerField(blank=True, null=True)),
                ('bathroom_number', models.SmallIntegerField(blank=True, null=True)),
                ('construcction_size', models.IntegerField(blank=True, null=True)),
                ('solar_size', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('city', models.CharField(choices=[('SD', 'Santo Domingo'), ('SC', 'San Cristobal'), ('SA', 'Santiago')], default='SD', max_length=4)),
                ('deleted', models.BooleanField(default=False)),
                ('propietary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propietary.Propietary')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.place_rent.helpers.user_house_directory_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='place_rent.HouseRent')),
            ],
        ),
    ]
