# Generated by Django 2.2.3 on 2019-07-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseimage',
            old_name='property_id',
            new_name='property_place',
        ),
    ]
