# Generated by Django 2.2.3 on 2019-07-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietary',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
